# Generated by Django 4.2.4 on 2023-09-26 13:07

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.CharField(default=orders.models.get_order_number, editable=False, max_length=256, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('status', models.CharField(choices=[('in_process', 'В обработке'), ('confirmed', 'Подтвержден'), ('waiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('assembly', 'Собирается'), ('on_way', 'В пути'), ('delivery_point', 'В пунке выдачи'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='in_process', max_length=50)),
                ('payment', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('deliviry', models.CharField(max_length=50, verbose_name='Способ доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.products')),
            ],
        ),
    ]
